easy_admin:
    site_name: 'Management pane'

    formats:
      date:     'd/m/Y'
      time:     'H:i'
      datetime: 'd/m/Y H:i:s'

    design:
        menu:
          - { label: 'Internations coding test'}
          - User
          - Group
    entities:
        User:
          class: App\Entity\User
          label: 'Users'
          list:
            title: '%%entity_label%%'
            fields:
              - id
              - name
              - { property: 'email', type: 'email' }
              - isAdmin
              - updated
          form:
            fields:
              - { property: 'email', type: 'email' }
              - { property: 'password', type: 'password' }
              - firstName
              - lastName
              - isAdmin
              - { property: 'groups', type: 'entity',  type_options: { expanded: false, multiple: true } }
              - { property: 'created', type: 'datetime', nullable: false, type_options: { widget: 'single_text', disabled: true} }
              - { property: 'updated', type: 'datetime', nullable: false, type_options: { widget: 'single_text', disabled: true } }
        Group:
          class: App\Entity\Group
          label: 'Groups'
          list:
            title: '%%entity_label%%'
#            actions:
#              - { label: 'Delete', name: 'deleteGroup' }
            fields:
              - id
              - name
              - users
              - updated
          form:
            fields:
              - name
              - { property: 'users', type: 'entity',  type_options: { expanded: false, multiple: true } }
              - { property: 'created', type: 'datetime', nullable: false, type_options: { widget: 'single_text', disabled: true} }
              - { property: 'updated', type: 'datetime', nullable: false, type_options: { widget: 'single_text', disabled: true } }
