# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener: true
    body_converter: true
#    disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener: true

    exception:
        enabled:              true
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            App\Exception\FormValidationException: 400
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        enabled: true
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            #- { path: '^/', stop: true } # Available for version >= 1.5
