#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api:
  type: rest
  resource: App\Controller\ApiController

app.swagger_ui:
  path: /api
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }